version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    command: sleep infinity
    volumes:
      - ../..:/workspaces/heatsync
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    network_mode: "host"
    command: >
      /bin/sh -c "
      echo 'listener 1884 0.0.0.0' > /mosquitto/config/mosquitto.conf
      && echo 'allow_anonymous true' >> /mosquitto/config/mosquitto.conf
      && mosquitto -c /mosquitto/config/mosquitto.conf
      "

volumes:
  postgres-data:
